max_links: 2000
cron_generate: true
cron_generate_interval: 0
remove_duplicates: true
skip_untranslated: false
batch_process_limit: 1500
base_url: 'https://tome.fyi'
custom_links_include_images: false
excluded_languages: {  }
enabled_entity_types:
  - node
  - taxonomy_term
  - menu_link_content
_core:
  default_config_hash: vFARRSP9-YgEArfDNYmRSg0cNFOgZPxqziffIalgLbU
